### ISSUE TITLE
Wrong VF order in 8xy6 and 8xyE

### ISSUE THREAD

**Issue by gulrak** [kurtjd/jaxe#21]
First of all: Nice project, nice compact implementation and good that there is libretro support as I couldn't get myself doing it. :-)

In all math operations that set a flag result in VF and VF is also Vx, the result register, the result of the operation needs to be the flag result of the operation, not the operation result. This is order is wrong in 8xy6 and 8xyE leading to e.g. VF always being 0 for in case of 8xy6 and a potential flag result of 2 in case of 8xyE.

The flags test of Timendus great test suite can be used to verify this: https://github.com/Timendus/chip8-test-suite#flags-test

JAXE result is:

<img width="752" alt="Bildschirmfoto 2024-03-31 um 10 53 24" src="https://github.com/kurtjd/jaxe/assets/1897322/c1e71ffe-dc64-4afd-a27f-672792faa2af">

So as expected 8xy6 and 8xyE failed the VF order test. This is btw. an error in many emulators as it is described misleadingly in Cowgod's technical reference and Wikipedia.

**Comment by kurtjd** [comment]
Awesome, nice catch, thanks! Thought I had 100% passed Timendus' test suite but guess I missed this one. I will work on getting this fixed.

**Comment by kurtjd** [comment]
Should be fixed now, thanks again!

**Comment by kurtjd** [comment]
Should be fixed now, thanks again!

**Comment by gulrak** [comment]
Thank you for fixing it!
